# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/service_container.html
parameters:
    app.model.address: AppBundle\Entity\Address
    app.model.election: AppBundle\Entity\Election
    app.model.election_round: AppBundle\Entity\ElectionRound
    app.model.office: AppBundle\Entity\Office
    app.model.procuration: AppBundle\Entity\Procuration
    app.model.voting_availability: AppBundle\Entity\VotingAvailability
    app.model.voter_invitation: AppBundle\Entity\VoterInvitation

services:
    app.fpdi.writer:
        class: AppBundle\FPDI\FPDIWriter
        arguments:
            - "%cerfa_source_file_path%"
            - "@app.mediator.procuration"
            - "@filesystem"
    app.generator.password:
        class: AppBundle\Generator\PasswordGenerator


    app.twig.procuration_extension:
        class: AppBundle\Twig\ProcurationExtension
        public: false
        tags:
            - { name: twig.extension }
        arguments:
            - "@app.form.handler.procuration_assignation"
    app.twig.ui_extension:
        class: AppBundle\Twig\UiExtension
        public: false
        tags:
            - { name: twig.extension }
        arguments:
            - "@app.mediator.user"
    twig.extension.intl:
        class: Twig_Extensions_Extension_Intl
        public: false
        tags:
            - { name: twig.extension }

